.nh
.TH "HASP" "1" "Sep 2026" "hasp" "hasp Manual"

.SH NAME
hasp-list-host - List every host stanza, scoped to one group with --group


.SH SYNOPSIS
\fBhasp list host [flags]\fP


.SH DESCRIPTION
List every host stanza, scoped to one group with --group


.SH OPTIONS
\fB--group\fP=""
	scope to one host group's short name (e.g. "work" for work.sshconfig)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for host


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--json\fP[=false]
	machine-readable output

.PP
\fB--key-dir\fP="~/.ssh"
	key directory (default ~/.ssh)

.PP
\fB--no-color\fP[=false]
	disable ANSI color in human output

.PP
\fB--verbose\fP[=false]
	enable diagnostic logging to stderr

.PP
\fB--yes\fP[=false]
	consent to apply a write non-interactively


.SH SEE ALSO
\fBhasp-list(1)\fP
