.nh
.TH "HASP" "1" "Sep 2026" "hasp" "hasp Manual"

.SH NAME
hasp-show-key - Show full detail for one key: identity, locations, profiles, and bound hosts


.SH SYNOPSIS
\fBhasp show key  [flags]\fP


.SH DESCRIPTION
Show full detail for one key: identity, locations, profiles, and bound hosts


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for key


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--json\fP[=false]
	machine-readable output

.PP
\fB--key-dir\fP="~/.ssh"
	key directory (default ~/.ssh)

.PP
\fB--no-color\fP[=false]
	disable ANSI color in human output

.PP
\fB--verbose\fP[=false]
	enable diagnostic logging to stderr

.PP
\fB--yes\fP[=false]
	consent to apply a write non-interactively


.SH SEE ALSO
\fBhasp-show(1)\fP
