.nh
.TH "HASP" "1" "Sep 2026" "hasp" "hasp Manual"

.SH NAME
hasp-release - Move a managed resource back out of managed territory (inverse of adopt)


.SH SYNOPSIS
\fBhasp release [flags]\fP


.SH DESCRIPTION
Move a managed resource back out of managed territory (inverse of adopt)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for release


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--json\fP[=false]
	machine-readable output

.PP
\fB--key-dir\fP="~/.ssh"
	key directory (default ~/.ssh)

.PP
\fB--no-color\fP[=false]
	disable ANSI color in human output

.PP
\fB--verbose\fP[=false]
	enable diagnostic logging to stderr

.PP
\fB--yes\fP[=false]
	consent to apply a write non-interactively


.SH SEE ALSO
\fBhasp(1)\fP, \fBhasp-release-host(1)\fP, \fBhasp-release-key(1)\fP, \fBhasp-release-profile(1)\fP
