.nh
.TH "HASP" "1" "Sep 2026" "hasp" "hasp Manual"

.SH NAME
hasp-find-profile - Match by name fragment


.SH SYNOPSIS
\fBhasp find profile  [flags]\fP


.SH DESCRIPTION
Match by name fragment


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for profile


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--json\fP[=false]
	machine-readable output

.PP
\fB--key-dir\fP="~/.ssh"
	key directory (default ~/.ssh)

.PP
\fB--no-color\fP[=false]
	disable ANSI color in human output

.PP
\fB--verbose\fP[=false]
	enable diagnostic logging to stderr

.PP
\fB--yes\fP[=false]
	consent to apply a write non-interactively


.SH SEE ALSO
\fBhasp-find(1)\fP
