.nh
.TH "HASP" "1" "Sep 2026" "hasp" "hasp Manual"

.SH NAME
hasp-edit - Change an existing resource in place: rename, alias, replace material, or relocate


.SH SYNOPSIS
\fBhasp edit [flags]\fP


.SH DESCRIPTION
Change an existing resource in place: rename, alias, replace material, or relocate


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for edit


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--json\fP[=false]
	machine-readable output

.PP
\fB--key-dir\fP="~/.ssh"
	key directory (default ~/.ssh)

.PP
\fB--no-color\fP[=false]
	disable ANSI color in human output

.PP
\fB--verbose\fP[=false]
	enable diagnostic logging to stderr

.PP
\fB--yes\fP[=false]
	consent to apply a write non-interactively


.SH SEE ALSO
\fBhasp(1)\fP, \fBhasp-edit-host(1)\fP, \fBhasp-edit-key(1)\fP
