// Command gendocs generates hasp's user-facing reference surface — man pages, shell completions,
// and a CLI reference under docs/cli/ — from the cobra command tree itself
// (docs/tech-decision-log.md#t34, docs/tdd.md §17 "The `Docs` target"). T34's decision is that
// this surface is generated wherever it can drift out of step with the binary, and CI fails if the
// committed copy has gone stale. It is a development-time tool, run via `go run ./tools/gendocs`
// from the repo root and wired as the `GenDocs` (regenerate) and `Docs` (`-check`, staleness gate)
// Mage targets — never imported by hasp itself, and never exec'd by hasp at runtime.
//
// Two modes, selected by -check:
//
//   - Default: generate-and-overwrite. docs/cli/, manpages/, and completions/ are each removed and
//     recreated from scratch (so a removed command's stale file never lingers), then freshly
//     generated content is written into them. This is the dev-time "regenerate and commit"
//     workflow.
//   - -check: generate into a temp directory, then diff that recursively, file by file, against
//     the three committed directories, reporting every mismatch to stderr. It never writes to the
//     working tree, which is what makes it safe to run in CI.
//
// Reproducibility gotcha (do not "fix" this back to time.Now()): cobra's markdown generator
// appends an "Auto generated by spf13/cobra on <today>" footer by default, and
// doc.GenManHeader.Date defaults to time.Now() when left nil. Either one would make every
// regeneration byte-different from the committed copy even when nothing about the command tree
// actually changed, which defeats the -check diff entirely — every CI run would report drift.
// root.DisableAutoGenTag suppresses the markdown footer outright; manPageDate is a fixed constant
// passed as GenManHeader.Date instead, bumped only when someone deliberately regenerates the
// reference for a real reason — the same way a real man page's date is bumped on release, not on
// every rebuild.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	"github.com/boweeb/hasp/internal/cli"
)

// manPageDate is pinned rather than time.Now() so regenerating the reference without any command
// tree change produces byte-identical output (see package doc). Bump this only when deliberately
// regenerating the reference for a real reason.
var manPageDate = time.Date(2026, 9, 5, 0, 0, 0, 0, time.UTC)

const (
	cliDocsDir     = "docs/cli"
	manPagesDir    = "manpages"
	completionsDir = "completions"
)

func main() {
	check := flag.Bool("check", false, "diff generated output against the committed copy instead of writing it")
	flag.Parse()

	if *check {
		if err := runCheck(); err != nil {
			fmt.Fprintln(os.Stderr, "gendocs:", err)
			os.Exit(1)
		}
		return
	}

	if err := runGenerate(cliDocsDir, manPagesDir, completionsDir); err != nil {
		fmt.Fprintln(os.Stderr, "gendocs:", err)
		os.Exit(1)
	}
}

// runGenerate removes and recreates cliDir, manDir, and compDir from scratch, then writes freshly
// generated content into them.
func runGenerate(cliDir, manDir, compDir string) error {
	for _, dir := range []string{cliDir, manDir, compDir} {
		if err := os.RemoveAll(dir); err != nil {
			return fmt.Errorf("remove %s: %w", dir, err)
		}
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("mkdir %s: %w", dir, err)
		}
	}
	return generateAll(cliDir, manDir, compDir)
}

// runCheck generates into a temp directory, then diffs it recursively against the three committed
// directories, reporting every mismatch before deciding pass/fail.
func runCheck() error {
	tmp, err := os.MkdirTemp("", "hasp-gendocs-check-*")
	if err != nil {
		return fmt.Errorf("create temp dir: %w", err)
	}
	defer func() { _ = os.RemoveAll(tmp) }()

	tmpCLI := filepath.Join(tmp, "cli")
	tmpMan := filepath.Join(tmp, "man")
	tmpComp := filepath.Join(tmp, "completions")
	for _, dir := range []string{tmpCLI, tmpMan, tmpComp} {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("mkdir %s: %w", dir, err)
		}
	}

	if err := generateAll(tmpCLI, tmpMan, tmpComp); err != nil {
		return err
	}

	var mismatches []string
	mismatches = append(mismatches, diffDirs(tmpCLI, cliDocsDir)...)
	mismatches = append(mismatches, diffDirs(tmpMan, manPagesDir)...)
	mismatches = append(mismatches, diffDirs(tmpComp, completionsDir)...)

	for _, m := range mismatches {
		fmt.Fprintln(os.Stderr, m)
	}
	fmt.Printf("gendocs: %d mismatch(es)\n", len(mismatches))
	if len(mismatches) > 0 {
		return fmt.Errorf("generated reference is stale (run `go run ./tools/gendocs` to regenerate)")
	}
	return nil
}

// generateAll builds the command tree once and writes the CLI reference, man pages, and shell
// completions into cliDir, manDir, and compDir respectively. It never removes anything — callers
// (runGenerate, runCheck) are responsible for starting from an empty target.
func generateAll(cliDir, manDir, compDir string) error {
	root := cli.NewRootCmd()
	// Suppress cobra's "Auto generated by spf13/cobra on <today>" markdown footer (see package
	// doc): left on, it would make every regeneration byte-different even with no real change.
	root.DisableAutoGenTag = true

	// --key-dir's real default is os.UserHomeDir()-resolved (internal/cli/root.go's
	// defaultKeyDir), which bakes the generating machine's literal $HOME into every usage string
	// cobra/pflag render — different on every machine and CI runner, and a leak of the author's
	// local path into committed docs. Normalize pflag.Flag.DefValue (exactly what cobra's
	// markdown/man formatters print) back to the placeholder before generating, so the reference
	// stays reproducible across machines.
	if f := root.PersistentFlags().Lookup("key-dir"); f != nil {
		f.DefValue = "~/.ssh"
	}

	if err := doc.GenMarkdownTree(root, cliDir); err != nil {
		return fmt.Errorf("generate markdown reference: %w", err)
	}

	header := &doc.GenManHeader{
		Title:   "HASP",
		Section: "1",
		Source:  "hasp",
		Manual:  "hasp Manual",
		Date:    &manPageDate,
	}
	if err := doc.GenManTree(root, header, manDir); err != nil {
		return fmt.Errorf("generate man pages: %w", err)
	}

	if err := generateCompletions(root, compDir); err != nil {
		return err
	}

	return nil
}

// generateCompletions writes the four shell-completion scripts cobra can produce for root into
// compDir.
func generateCompletions(root *cobra.Command, compDir string) error {
	targets := []struct {
		file string
		gen  func(w *os.File) error
	}{
		{"hasp.bash", func(w *os.File) error { return root.GenBashCompletionV2(w, true) }},
		{"hasp.zsh", func(w *os.File) error { return root.GenZshCompletion(w) }},
		{"hasp.fish", func(w *os.File) error { return root.GenFishCompletion(w, true) }},
		{"hasp.ps1", func(w *os.File) error { return root.GenPowerShellCompletionWithDesc(w) }},
	}

	for _, t := range targets {
		path := filepath.Join(compDir, t.file)
		f, err := os.Create(path)
		if err != nil {
			return fmt.Errorf("create %s: %w", path, err)
		}
		err = t.gen(f)
		closeErr := f.Close()
		if err != nil {
			return fmt.Errorf("generate %s: %w", path, err)
		}
		if closeErr != nil {
			return fmt.Errorf("close %s: %w", path, closeErr)
		}
	}
	return nil
}

// diffDirs recursively compares generated (a freshly-generated directory) against committed (the
// tracked copy in the repo), returning one human-readable mismatch string per missing file, extra
// file, or byte-differing file found. Both directories are walked independently and their relative
// file sets unioned, so a file present in only one of the two is reported rather than silently
// skipped.
func diffDirs(generated, committed string) []string {
	var mismatches []string

	genFiles, err := relFileSet(generated)
	if err != nil {
		return []string{fmt.Sprintf("%s: %v", generated, err)}
	}
	commFiles, err := relFileSet(committed)
	if err != nil {
		return []string{fmt.Sprintf("%s: %v", committed, err)}
	}

	all := make(map[string]bool, len(genFiles)+len(commFiles))
	for rel := range genFiles {
		all[rel] = true
	}
	for rel := range commFiles {
		all[rel] = true
	}

	for rel := range all {
		_, inGen := genFiles[rel]
		_, inComm := commFiles[rel]
		switch {
		case inGen && !inComm:
			mismatches = append(mismatches, fmt.Sprintf("%s: present in generated output but missing from committed %s", rel, committed))
		case !inGen && inComm:
			mismatches = append(mismatches, fmt.Sprintf("%s: present in committed %s but missing from generated output", rel, committed))
		default:
			genBytes, err := os.ReadFile(filepath.Join(generated, rel))
			if err != nil {
				mismatches = append(mismatches, fmt.Sprintf("%s: read generated copy: %v", rel, err))
				continue
			}
			commBytes, err := os.ReadFile(filepath.Join(committed, rel))
			if err != nil {
				mismatches = append(mismatches, fmt.Sprintf("%s: read committed copy: %v", rel, err))
				continue
			}
			if !bytes.Equal(genBytes, commBytes) {
				mismatches = append(mismatches, fmt.Sprintf("%s: content differs from committed %s", rel, committed))
			}
		}
	}

	return mismatches
}

// relFileSet walks dir and returns the set of regular files found, keyed by path relative to dir.
// A non-existent dir yields an empty set rather than an error, so a wholly-missing committed
// directory is reported per-file via diffDirs's "missing from committed" branch instead of a
// single opaque top-level error.
func relFileSet(dir string) (map[string]bool, error) {
	files := map[string]bool{}
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			if os.IsNotExist(err) && path == dir {
				return filepath.SkipDir
			}
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		files[rel] = true
		return nil
	})
	if err != nil && !os.IsNotExist(err) {
		return nil, err
	}
	return files, nil
}
